### PR TITLE
Allow attaching ASG to other target groups

### PR DESCRIPTION
**Pull request by jakjohnson**
Ignore changes to load_balancers and target_group_arns attributes.

The objective of this change is to allow for more flexibility in infrastructure customisations while not changing current behaviour. 

Currently, any changes to the ASG 'asg' that happen outside of this module, such as attaching it to another target group, get reverted once this module runs as described in the Terraform documentation (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group)

Having multiple target groups attached to this ASG can be useful for deployments that have 2 load balancers (ex: private and public).

### CODE REVIEW

**Comment by jbeemster** [comment]
Hi @jakjohnson not sure I am following why you wouldn't simply define all `target_group_arns` in this module?  I appreciate the want for flexibility but there is a clear dependency tree here where you create a Target Group and assign it to the ASG.

You can already attach multiple target groups to the ASG as per your comment - but you cannot handle that association externally to this module - could you provide an example of why this change is needed and why its not possible to associate the target_group with this module directly?

**Comment by jakjohnson** [comment]
Hi @jbeemster, we actually don't call this module directly but we use it though the `collector-kinesis-ec2` module which sets the `target_group_arns` argument to the value of the `collector_lb_tg_id` variable which is a string so only allows one value.

We have a deployment in which we have the same collector ASG attached to a HTTP target group and a TCP target group which are used respectively by an internet facing ALB (JS tracker events) and an internal NLB (backend events).

Since the ID of the ASG is an output of the `collector-kinesis-ec2` module, we can attach the collector ASG to the NLB  target group with a `aws_autoscaling_attachment` resource from the calling code (but these changes are currently being undone each time when changes are applied since `target_group_arns` gets updated). Ignoring future changes to `target_group_arns` effectively allows the ASG to be attached to multiple target groups.

An alternative would be to modify the `collector-kinesis-ec2` module to allow for more than one load balancer, IIUC this would require accepting a list of target group IDs to attach the ASG to and a list of source security groups. 

Please let me know if that seems like a more acceptable solution to you!

**Comment by jbeemster** [comment]
Hey @jakjohnson that makes a ton of sense!  Yes if you could please add that to the Collector stack instead that would be the preferred place to implement this.

**Comment by jakjohnson** [comment]
Sure thing, I'll close this PR and create another one there then.

**Pull request closed without merging**
